INCLUDE OPC.LIB
INCLUDE gato.LIB
.model tiny 
.stack 
.data 
TEXTO  	DB 	"TECNOLIGICO DE ESTUDIOS SUPERIORES DEL ORIENTE DEL ESTADO DE MEXICO$"
TEXTO1 	DB 	"MIGUEL VARGAS AXEL JACINTO$"
TEXTO2 	DB 	"6S11$"
TEXTO3 	DB 	"26/05/2022$"
TEXTO4 	DB 	"ENTER$"
TEXTO5 	DB 	"PROYECTO FINAL SEGUNDO PARCIAL: $"
TEXTO6 	DB 	"MENU$"
TEXTO7 	DB 	"1.-CREAR ARCHIVO Y AGREGAR INFORMACION$"
TEXTO8 	DB 	"2.-BORRAR ARCHIVO CREADO$"
TEXTO9 	DB 	"Seleccione una opcion:$"
TEXTO16 DB  "APLICAMOS TODOS LOS TEMAS VISTOS EN CLASE PARA QUE DE ESTA FORMA$"
TEXTO17 DB  "LOGREMOS COMPRENDER A MAYOR PROFUNIDAD EL LENGUAJE ENSAMBLADOR.$"

TEXTO10 DB 	"1.-CREAR ARCHIVO $" 
TEXTO11 DB  "2.-BORRAR ARCHIVO $"
TEXTO12 DB  "Seleccione:  $";
;---------variables PARA GUARDAR
SPACE 	DB 	"Seleccione una opcion:  $"
DAT1 	DB 	"SE HA CREADO EL ARCHIVO, ENTER PARA CONTINUAR$"
DAT2 	DB 	"SE HA ELIMINADO EL ARCHIVO, ENTER PARA CONTINUAR$"
SAVE 	LABEL BYTE
MAX 	DB 20
REALM 	DB ?
DATOSM 	DB 20 DUP('$')


TEXTO13 DB  "Escribe algunos datos para guardar: $";
TEXTO14 DB  "CREA ARCHIVO $";
nombre  DB  'C:\TASM\ARCHIVO2.txt',00H 					 
mane    DW       ?
ENT		LABEL	BYTE
MAXIMO	DB	20
REAL	DB	?
DATOS	DB	20 DUP('')
prueba 	DB 	"HOLA$"

.code						 ;directivas de asignamiento de segmentos  de datos
start:
begin PROC FAR				;INICIO DE PROCEDIMIENTO BEGIN
		MOV AX,0600H 		;PETICI�N
		MOV BH,07H 			;ATRIBUTO NEGRO SOBRE BLANCO
		MOV CX,0000H 		;INICIO
		MOV DX,184FH 		;FINAL
		INT 10H
	
		CALL MARCO	
		CALL MARCO2
		CALL MARCO3
		call MARCO4
		MOV AH,00H			;REGRESAMOS AL MODO TEXTO MOV AL,03H INT 10H
		MOV AL, 03H
		INT 10H
		
		MOV AX, 4C00H
		INT 21H
	
MARCO PROC NEAR

		MOV BH,00 			;N�MERO DE P�GINA 0
		MOV DH,12 			;RENGL�N
		MOV DL,15 			;COLUMNA
		INT 10H
	
;1  --- PINTA EL CENTRO
		MOV AX,0600H 		;PETICI�N
		MOV BH,30H 			;COLOR MARCO
		MOV CX,0000H 		;INICIO
		MOV DX,184FH 		;FINAL
		INT 10H
	
;2  -----PARTE SUPERIOR															 
		MOV AX,0600H 		;PETICI�N
		MOV BH,60H 			;COLOR MARCO
		MOV CX,0000H 		;INICIO
		MOV DX, 004FH 		;FINAL
		INT 10H
;3 ----- PARTE IZQUIERDA
		MOV AX,0600H 		;PETICI�N
		MOV BH,60H 			;COLOR MARCO
		MOV CX,0000H 		;INICIO
		MOV DX,1800H 		;FINAL
		INT 10H
;4  ------ PARTE INFERIOR
		MOV AX,0600H 		;PETICI�N
		MOV BH,60H 			;COLOR MARCO
		MOV CX,1800H 		;INICIO
		MOV DX,184FH 		;FINAL
		INT 10H
;5  ---- PARTE DERECHA
		MOV AX,0600H 		;PETICI�N
		MOV BH,60H 			;COLOR MARCO
		MOV CX,004FH 		;INICIO
		MOV DX,184FH 		;FINAL
		INT 10H
	
;SE TERMINAN DE PINTAR LOS BORDES DE LA PANTALLA
;COLOCAMOS DATOS EN LA PANTALLA

		MOV AH,02H 			;PETICION DEL CURSOR				
		MOV BH,00 			;PAGINA					
		MOV DH,04 			;REGLON				
		MOV DL,05			;COLUMNA
		INT 10H
		MOV AX, 00H 		;inicia mouse
		INT 33H
 	
		LEA DX,TEXTO 		;CARGA DE LA DIRRECCION
		MOV AX,SEG TEXTO	;SEGMENTO EN AX
		MOV DS,AX 			;DS:DX APUNTA AL mensaje
		MOV AH,09H 			;PETICI�N DE DESPLIEGE
		INT 21H 			;INTERRUPCI�N
;-------------------		
		MOV AH,02H 						
		MOV BH,00 						
		MOV DH,08 						
		MOV DL,25 
		INT 10h
 	
		LEA DX,TEXTO1		;CARGA DE LA DIRRECCION
		MOV AX,SEG TEXTO1 	;SEGMENTO EN AX
		MOV DS,AX 			;DS:DX APUNTA AL mensaje
		MOV AH,09H 			;PETICI�N DE DESPLIEGE
		INT 21H 			;INTERRUPCI�N
;-------------------		
		MOV AH,02H 						
		MOV BH,00 						
		MOV DH,12 						
		MOV DL,35 
		INT 10H
 	
		LEA DX,TEXTO2 		;CARGA DE LA DIRRECCION
		MOV AX,SEG TEXTO2	;SEGMENTO EN AX
		MOV DS,AX 			;DS:DX APUNTA AL mensaje
		MOV AH,09H 			;PETICI�N DE DESPLIEGE
		INT 21H 			;INTERRUPCI�N
;-------------------		
		MOV AH,02H 						
		MOV BH,00 						
		MOV DH,16 						
		MOV DL,32
		INT 10H
 	
		LEA DX,TEXTO3 		;CARGA DE LA DIRRECCION
		MOV AX,SEG TEXTO3 	;SEGMENTO EN AX
		MOV DS,AX 			;DS:DX APUNTA AL mensaje
		MOV AH,09H 			;PETICI�N DE DESPLIEGE
		INT 21H 			;INTERRUPCI�N
;-------------------		
		MOV AH,02H 			;PETICIÓN PARA COLOCAR EL CURSOR
		MOV BH,00 			;PÁGINA
		MOV DH,22 			;RENGLÓN
		MOV DL,64 			;COLUMNA
		INT 10H

		LEA DX,TEXTO4 		;CARGA DE LA DIRRECCION
		MOV AX,SEG TEXTO4 	;SEGMENTO EN AX
		MOV DS,AX 			;DS:DX APUNTA AL MENSAJE
		MOV AH,09H 			;PETICIÓN DE DESPLIEGE
		INT 21H 			;INTERRUPCIÓN
;-------------------	
;-----------------------------------------------BOTON  1-----------------------------------
		MOV AX,0600H 		;PETICI�N
		MOV BH,70H 			;ATRIBUTO NEGRO SOBRE BLANCO
		MOV CX,1537H 		;INICIO
		MOV DX,174EH 		;FINAL
		INT 10H
;-------------------	
		MOV AH,02H 			;PETICIÓN PARA COLOCAR EL CURSOR
        MOV BH,00 			;PÁGINA
        MOV DH,22 			;RENGLÓN
        MOV DL,64 			;COLUMNA
        INT 10H

        LEA DX,TEXTO4 		;CARGA DE LA DIRRECCION
        MOV AX,SEG TEXTO4 	;SEGMENTO EN AX
        MOV DS,AX 			;DS:DX APUNTA AL MENSAJE
        MOV AH,09H 			;PETICIÓN DE DESPLIEGE
        INT 21H 			;INTERRUPCIÓN
;-------------------	
;------------------MOVIMIENTO BOTON 1 ----------------------
		MOV CX,0FH
		MOV DX,4129H
		MOV AH,86H
		INT 15H
		
		MOV AX,0600H 		;PETICI�N
		MOV BH,40H 			;COLOR ROJO
		MOV CX,1537H 		;INICIO
		MOV DX,174EH 		;FINAL
		INT 10H
;-------------------	
		MOV AH,02H 			;PETICIÓN PARA COLOCAR EL CURSOR
        MOV BH,00 			;PÁGINA
        MOV DH,22 			;RENGLÓN
        MOV DL,64 			;COLUMNA
        INT 10H

        LEA DX,TEXTO4 		;CARGA DE LA DIRRECCION
        MOV AX,SEG TEXTO4 	;SEGMENTO EN AX
        MOV DS,AX 			;DS:DX APUNTA AL MENSAJE
        MOV AH,09H 			;PETICIÓN DE DESPLIEGE
        INT 21H 			;INTERRUPCIÓN
;-------------------	
;------------------MOVIMIENTO BOTON 1 ----------------------
		MOV CX,0FH
		MOV DX,4129H
		MOV AH,86H
		INT 15H
		CALL PAUSA
;FIN DEL BOTON
		RET	
MARCO ENDP
MARCO2 PROC NEAR
		MOV AX,0600H 		;PETICI�N
		MOV BH,60H 			;ATRIBUTO NEGRO SOBRE BLANCO
		MOV CX,0000H 		;INICIO
		MOV DX,184FH 		;FINAL
		INT 10h
;------------------------------PINTAR  MARCO 2 ---------------------------
;1  --- PINTA EL CENTRO
		MOV AX,0600H 		;PETICI�N
		MOV BH,50H 			;ATRIBUTO NEGRO SOBRE BLANCO
		MOV CX,0000H 		;INICIO
		MOV DX, 004FH 		;FINAL
		INT 10H
;2  -----PARTE SUPERIOR	
		MOV AX,0600H 		;PETICI�N
		MOV BH,50H 			;ATRIBUTO NEGRO SOBRE BLANCO
		MOV CX,0000H 		;INICIO
		MOV DX,1800H 		;FINAL
		INT 10H
;3 ----- PARTE IZQUIERDA
		MOV AX,0600H 		;PETICI�N
		MOV BH,50H 			;ATRIBUTO NEGRO SOBRE BLANCO
		MOV CX,0000H 		;INICIO
		MOV DX,1800H 		;FINAL
		INT 10H
;4  ------ PARTE INFERIOR
		MOV AX,0600H 		;PETICI�N
		MOV BH,50H 			;ATRIBUTO NEGRO SOBRE BLANCO
		MOV CX,1800H 		;INICIO
		MOV DX,184FH 		;FINAL
		INT 10H
;5  ---- PARTE DERECHA
		MOV AX,0600H 		;PETICI�N
		MOV BH,50H 			;ATRIBUTO NEGRO SOBRE BLANCO
		MOV CX,004FH 		;INICIO
		MOV DX,184FH 		;FINAL
		INT 10H
	
;---------------- TERMINAMOS DE PINTAR EL MARCO DE LA SEGUNDA PANTALLA --------------
							;inicion del texto
		MOV AH,02H 			;PETICION DEL CURSOR	
		MOV BH,00   		;NUMERO DE PAGINA 						
		MOV DH,04			;FILA				
		MOV DL,05			;COLUMNA
		INT 10H
		
		LEA DX,TEXTO5 		;CARGA DE LA DIRRECCION
		MOV AX,SEG TEXTO5 	;SEGMENTO EN AX
		MOV DS,AX 			;DS:DX APUNTA AL mensaje
		MOV AH,09H 			;PETICI�N DE DESPLIEGE
		INT 21H 			;INTERRUPCI�N
;------------------- TEXTO INTRODUCCION
								;inicion del texto
		MOV AH,02H 			;PETICION DEL CURSOR	
		MOV BH,00   		;NUMERO DE PAGINA 						
		MOV DH,06			;FILA				
		MOV DL,05			;COLUMNA
		INT 10H

		LEA DX,TEXTO16 		;CARGA DE LA DIRRECCION
		MOV AX,SEG TEXTO16 	;SEGMENTO EN AX
		MOV DS,AX 			;DS:DX APUNTA AL MENSAJE
		MOV AH,09H 			;PETICIÓN DE DESPLIEGE
		INT 21H 			;INTERRUPCIÓN
;------------------- 
		MOV AH,02H 			;PETICION DEL CURSOR	
		MOV BH,00   		;NUMERO DE PAGINA 						
		MOV DH,07			;FILA				
		MOV DL,05			;COLUMNA
		INT 10H

		LEA DX,TEXTO17 		;CARGA DE LA DIRRECCION
		MOV AX,SEG TEXTO17 	;SEGMENTO EN AX
		MOV DS,AX 			;DS:DX APUNTA AL MENSAJE
		MOV AH,09H 			;PETICIÓN DE DESPLIEGE
		INT 21H 			;INTERRUPCIÓN
	
;------------------ INICIO BOTON 2 ------------------
		MOV AX,0600H 		;PETICI�N
		MOV BH,30H 			;ATRIBUTO NEGRO SOBRE BLANCO
		MOV CX,1537H 		;INICIO
		MOV DX,174EH 		;FINAL
		INT 10H
;-------------------		
		MOV AH,02H 			;PETICIÓN PARA COLOCAR EL CURSOR
		MOV BH,00 			;Página
		MOV DH,22 			;RENGLÓN
		MOV DL,64 			;COLUMNA
		INT 10H

        LEA DX,TEXTO4 		;CARGA DE LA DIRRECCION
        MOV AX,SEG TEXTO4 	;SEGMENTO EN AX
        MOV DS,AX 			;DS:DX APUNTA AL MENSAJE
        MOV AH,09H 			;PETICIÓN DE DESPLIEGE
        INT 21H 			;INTERRUPCIÓN
;-------------------	
;----------------------MOVIMIENTO DE BOTON 2-----------------------------
		MOV CX,0FH
		MOV DX,4129H
		MOV AH,86H
		INT 15H
;-------------------
		MOV AH,02H 			;PETICIÓN PARA COLOCAR EL CURSOR
        MOV BH,00 			;PÁGINA
        MOV DH,22 			;RENGLÓN
        MOV DL,64 			;COLUMNA
        INT 10H

        LEA DX,TEXTO4 		;CARGA DE LA DIRRECCION
        MOV AX,SEG TEXTO4 	;SEGMENTO EN AX
        MOV DS,AX 			;DS:DX APUNTA AL MENSAJE
        MOV AH,09H 			;PETICIÓN DE DESPLIEGE
        INT 21H 			;INTERRUPCIÓN
;-------------------
;----------------------MOVIMIENTO DE BOTON 2-----------------------------
		MOV CX,0FH
		MOV DX,4129H
		MOV AH,86H
		INT 15H
	
							;LLAMAMOS AL MOUSE
		MOV AX,00H 			;MOVIMIENTO DE MOUSE ----
		INT 33H

		MOV AX,01H			;MUESTRA CURSOR
		INT 33H 

curs: 
		mov ax,03h 			;SE QUEDA SIN HACER NADA
		int 33h 
		cmp bx,2 			;HASTA QUE PRESIONES CLICK DERECHO
		je salir 
		jmp curs 
saLir:
		MOV AX, 02H			;OCULTA EL MOUSE
        INT 33H
      
        MOV AH, 00H			;RESTAURA INCIAL
        MOV AL, 03H
        INT 10H 
       
							;Puede ajustar el tamaño del cursor entre la parte superior y la inferior: 0:14 para VGA, 
        					;0:13 para monocromático y EGA y 0:7 para CGA. Para un VGA
							;FIN DEL BOTON 2
MARCO2 ENDP
;----------------------------------FIN DEL SEGUNDO MARCO---------------------------

;--------------------------------------MARCO 3-------------------------------------
MARCO3 PROC NEAR
		CALL GRAPHICS
	 						;INICIO DE TERCERA PANTALLA
	
		MOV AX,0600H 		;PETICI�N
		MOV BH,30H 			;ATRIBUTO NEGRO SOBRE BLANCO
		MOV CX,0000H 		;INICIO
		MOV DX,184FH 		;FINAL
		INT 10h
							;------------------SE PINTA EL MARCO----------------
;1  --- PINTA EL CENTRO
		MOV AX,0600H 		;PETICI�N
		MOV BH,10H 			;ATRIBUTO NEGRO SOBRE BLANCO
		MOV CX,0000H 		;INICIO
		MOV DX, 004FH 		;FINAL
		INT 10H
;2  -----PARTE SUPERIOR
		MOV AX,0600H 		;PETICI�N
		MOV BH,10H 			;ATRIBUTO NEGRO SOBRE BLANCO
		MOV CX,0000H 		;INICIO
		MOV DX,1800H 		;FINAL
		INT 10H
;3 ----- PARTE IZQUIERDA
		MOV AX,0600H 		;PETICI�N
		MOV BH,10H 			;ATRIBUTO NEGRO SOBRE BLANCO
		MOV CX,0000H 		;INICIO
		MOV DX,1800H 		;FINAL
		INT 10H
;4  ------ PARTE INFERIOR
		MOV AX,0600H 		;PETICI�N
		MOV BH,10H 			;ATRIBUTO NEGRO SOBRE BLANCO
		MOV CX,1800H 		;INICIO
		MOV DX,184FH 		;FINAL
		INT 10H

		MOV AX,0600H 		;PETICI�N
		MOV BH,10H 			;ATRIBUTO NEGRO SOBRE BLANCO
		MOV CX,004FH 		;INICIO
		MOV DX,184FH 		;FINAL
		INT 10H
;----------------------------------INICIO DEL TEXTO-----------------
;------------------------------DATOS--------------------------------
		MOV AH,02H 			;PETICION DEL CURSOR				
		MOV BH,00 			;PAGINA					
		MOV DH,03 			;REGLON				
		MOV DL,35			;COLUMNA
		INT 10H
 	
		LEA DX,TEXTO6 		;CARGA DE LA DIRRECCION
		MOV AX,SEG TEXTO6	;SEGMENTO EN AX
		MOV DS,AX 			;DS:DX APUNTA AL mensaje
		MOV AH,09H 			;PETICI�N DE DESPLIEGE
		INT 21H 			;INTERRUPCI�N
;-------------------		
		MOV AH,02H 			;PETICION DEL CURSOR				
		MOV BH,00 			;PAGINA					
		MOV DH,06 			;REGLON				
		MOV DL,14			;COLUMNA
		INT 10H
		
		LEA DX,TEXTO7 		;CARGA DE LA DIRRECCION
		MOV AX,SEG TEXTO7	;SEGMENTO EN AX
		MOV DS,AX 			;DS:DX APUNTA AL mensaje
		MOV AH,09H 			;PETICI�N DE DESPLIEGE
		INT 21H 			;INTERRUPCI�N	
;-------------------
		MOV AH,02H 			;PETICION DEL CURSOR				
		MOV BH,00 			;PAGINA					
		MOV DH,09 			;REGLON				
		MOV DL,14			;COLUMNA
		INT 10H
		
		LEA DX,TEXTO8 		;CARGA DE LA DIRRECCION
		MOV AX,SEG TEXTO8	;SEGMENTO EN AX
		MOV DS,AX 			;DS:DX APUNTA AL mensaje
		MOV AH,09H 			;PETICI�N DE DESPLIEGE
		INT 21H 			;INTERRUPCI�N
;-------------------	
		MOV AH,02H 			;PETICION DEL CURSOR				
		MOV BH,00 			;PAGINA					
		MOV DH,12 			;REGLON				
		MOV DL,14			;COLUMNA
		INT 10H
 	
		LEA DX,TEXTO9 		;CARGA DE LA DIRRECCION
		MOV AX,SEG TEXTO9	;SEGMENTO EN AX
		MOV DS,AX 			;DS:DX APUNTA AL mensaje
		MOV AH,09H 			;PETICI�N DE DESPLIEGE
		INT 21H 			;INTERRUPCI�N

;--------------------------------AQUI TERMINA EJECUCION DEL PROGRAMA PRINCIPAL------------dd

;--------------------------------SUBRUTINAS O FUNCIONES QUE SE LLAMAN DURANTE LA EJECUCUION DEL PROGRAMA-----------------------------
	
GRAPHICS PROC NEAR 
;------------------------INICIO EL MENU---------------------------
        MENU:
		MOV AX,0600H 		;PETICI�N
		MOV BH,0009H 		;ATRIBUTO NEGRO SOBRE BLANCO
		MOV CX,0000H 		;INICIO
		MOV DX,184FH 		;FINAL
		INT 10H
	
		MOV CX, 00 			;CX = COORD. X
		MOV DX, 00 			;DX = COORD Y


        MOV AH,02H 			;PETICI?N PARA COLOCAR EL CURSOR
		MOV BH,00 			;PAGINA
		MOV DH,02 			;RENGL?N
		MOV DL,40 			;COLUMNA
		INT 10H 

        LEA DX,TEXTO9   	;CARGA DE LA DIRRECCION
        MOV AX,SEG TEXTO9	;segmento en AX
        MOV DS,AX       	;DS:DX apunta al mensaje
        MOV AH,09H      	;PETICION DE DESPLIEGE
        INT 21H         	;INTERRUPCION


        MOV AH,02H 			;PETICI?N PARA COLOCAR EL CURSOR
		MOV BH,00 			;PAGINA
		MOV DH,06 			;RENGL?N
		MOV DL,02 			;COLUMNA
		INT 10H
    
		LEA DX,TEXTO10 		;CARGA DE LA DIRRECCION
		MOV	AX,SEG TEXTO10	;SEGMENTO EN AX
		MOV DS,AX 			;DS:DX APUNTA AL MENSAJE
		MOV AH,09H 			;PETICI?N DE DESPLIEGE
		INT 21H 			;INTERRUPCI?N
        
        MOV AH,02H 			;PETICI?N PARA COLOCAR EL CURSOR
		MOV BH,00 			;PAGINA
		MOV DH,08 			;RENGL?N
		MOV DL,02 			;COLUMNA
		INT 10H
    
		LEA DX,TEXTO11 		;CARGA DE LA DIRRECCION
		MOV	AX,SEG TEXTO11	;SEGMENTO EN AX
		MOV DS,AX 			;DS:DX APUNTA AL MENSAJE
		MOV AH,09H 			;PETICI?N DE DESPLIEGE
		INT 21H 			;INTERRUPCI?N

        MOV AH,02H 			;PETICI?N PARA COLOCAR EL CURSOR
		MOV BH,00 			;PAGINA
		MOV DH,10 			;RENGL?N
		MOV DL,02 			;COLUMNA
		INT 10H
    
		LEA DX,TEXTO12 		;CARGA DE LA DIRRECCION
		MOV	AX,SEG TEXTO12	;SEGMENTO EN AX
		MOV DS,AX 			;DS:DX APUNTA AL MENSAJE
		MOV AH,09H 			;PETICI?N DE DESPLIEGE
		INT 21H 			;INTERRUPCI?N

       

        MOV AH,02H 						
		MOV BH,00 						
		MOV DH,10 						
		MOV DL,12
		INT 10H
 	
		LEA DX,SPACE    	;CARGA DE LA DIRRECCION
		MOV AX,SEG SPACE    ;segmento en AX
		MOV DS,AX           ;DS:DX apunta al mensaje
		MOV AH,09H          ;PETICION DE DESPLIEGE
		INT 21H             ;INTERRUPCION	

		MOV	AH,0AH			;GUARDA DATO
		LEA	DX,SAVE
		INT 21H
		LEA DX, DATOSM
		MOV AH,09H
		

		MOV DL, DATOSM
		
		CMP DL, 31H
		JE OPC1
		CMP DL, 32H
		JE OPC2
;---------------TERMINA Y EMPIEZA PARA ESCOGER LA OPCION------------
		RET
GRAPHICS ENDP

OPC1 PROC NEAR
		OPC  				;lLAMAMOS A LA MACRO OPCION
		RET
OPC1 ENDP

OPC2 PROC NEAR

		MOV ax,SEG nombre     
		MOV ds,ax  
		LEA DX,nombre
		mov ah,41h
		int 21h
		MOV AH,02H 						
		MOV BH,00 						
		MOV DH,15 						
		MOV DL,12
		INT 10H
		LEA DX,DAT2        ;CARGA DE LA DIRRECCION
		MOV AX,SEG DAT2    ;segmento en AX
		MOV DS,AX          ;DS:DX apunta al mensaje
		MOV AH,09H         ;PETICION DE DESPLIEGE
		INT 21H            ;INTERRUPCION
		CALL PAUSA
		JMP MENU
		RET
OPC2 ENDP 

OPC3 PROC NEAR
		MOV AH,00H			;REGRESAMOS AL MODO TEXTO
		MOV AL,03H
		INT 10H
		MOV AX,4C00H 		;vuelta al DOS
		INT 21H
		RET
OPC3 ENDP 
		JMP MENU

;CALL PAUSA

MARCO3 ENDP
	 
MARCO4 PROC NEAR
;--------------INCIO DE LA TERCERA PANTALLA----------
		MOV    AH,00H 		;PETICION PARA HABILITAR MODO VIDEO
		MOV    AL,0DH 		;320 X 200 VGA
		INT    10H

		MOV    AH,0BH 		;ESTABLECE LA PALETA DE 16 COLORES
		MOV    BX,00AFH 	;BH PAGE, BL COLOR
		INT    10H 			;PARA EL FONDO DE PANTALLA
	 
		gato  				;LLAMAMOS A LA MACRO DIBUJO
MARCO4 ENDP
PAUSA PROC NEAR
		MOV AH, 10h 		;PAUSA
		INT 16h
		RET
PAUSA ENDP
		MOV AH,00H			;REGRESAMOS AL MODO TEXTO
		MOV AL,03H
		INT 10H
		MOV AX,4C00H 		;vuelta al DOS
		INT 21H

BEGIN ENDP 					;FIN DE PROCEDIMIENTO
END start 					;FIN DE PROGRAMA